### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by eblchen** [cliffzhou92/MuTrans-release#2]
Hi, I've been trying to use MuTrans and probably just missed something silly, but could you help me fix this error:
![image](https://github.com/cliffzhou92/MuTrans-release/assets/123748472/ceded6b1-ccbd-48c1-8220-51658337be4c)

**Comment by cliffzhou92** [comment]
It

> Hi, I've been trying to use MuTrans and probably just missed something silly, but could you help me fix this error: ![image](https://user-images.githubusercontent.com/123748472/257575048-ceded6b1-ccbd-48c1-8220-51658337be4c.png)

It seems that the adata.X is a csr matrix while the input is expected to be a numpy array. Would adata.X = adata.X.toarray() work?

**Comment by cliffzhou92** [comment]
> Hi, I've been trying to use MuTrans and probably just missed something silly, but could you help me fix this error: ![image](https://user-images.githubusercontent.com/123748472/257575048-ceded6b1-ccbd-48c1-8220-51658337be4c.png)

It seems that the adata.X is a csr matrix while the input is expected to be a numpy array. Would adata.X = adata.X.toarray() work?

**Comment by eblchen** [comment]
Thanks for getting back to me! I tried your suggestion, now this error comes up?
![image](https://github.com/cliffzhou92/MuTrans-release/assets/123748472/5a108273-f264-4f28-b76b-1fa9cabe2458)

**Comment by cliffzhou92** [comment]
> Thanks for getting back to me! I tried your suggestion, now this error comes up? ![image](https://user-images.githubusercontent.com/123748472/259461153-5a108273-f264-4f28-b76b-1fa9cabe2458.png)

Hi Emilia,

That's because the input number of cells (~49K) might be too large for the Matlab kernel to process transition matrix. Although it's possible to reset configuration in Matlab, a direct solution is to use the "reduction" method provided by MuTrans -- which is in your last line (commented), by setting "reduce_large_scale" and "reduce_num_meta_cell" keys in the par. More detailed usage can be found in  [example_bone_marrow-new.ipynb](https://github.com/cliffzhou92/MuTrans-release/blob/main/Example/example_bone_marrow-new.ipynb) and [example_haem_development_15K.ipynb](https://github.com/cliffzhou92/MuTrans-release/blob/main/Example/example_haem_development_15K.ipynb).

An alternate solution is to subsample the adata (e.g. using scanpy.pp.subsample) to around 2K-5K cells and apply dynamical analysis without "reduce_large_scale" method. Feel free to let me know if you need more information with your data analysis. I can also be reached via peijiez1@uci.edu directly.

**Comment by eblchen** [comment]
Thanks will give that a go !
